### ISSUE TITLE
Jenny script fails due to readlink on OSX

### ISSUE THREAD

**Issue by triggerNZ** [bmustiata/jenny#14]
On my Mac, running:

```
./jenny
```

gives me

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

A workaround i found on my system is changing readlink to greadlink (I think greadlink is the gnu one coming from `brew install coreutils`), but it would be nice to do some OS checking at the beginning of the script and making this work cross-platform without dependencies

**Comment by bmustiata** [comment]
Note for fix - replace readlink with a shell function: https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

@triggerNZ thank you for the bug report.
