### ISSUE TITLE
missing commands

### ISSUE THREAD

**Issue by mpictor** [bmustiata/jenny#27]
I know you don't support all jenkins commands, and matching it 90% would probably be quite difficult.

So, FWIW - these are in the Jenkinsfile I'm fiddling with, and they trip jenny up. Perhaps they're simple enough or popular enough for you to consider supporting.

```groovy

//does not recognize skipStagesAfterUnstable()
skipStagesAfterUnstable()

//does not recognize timeout()
timeout(time: 2, unit: 'HOURS') {
  //...
}

try {
  //...
}
 //does not recognize hudson.AbortException
catch (hudson.AbortException e) {
  //...
}


//does not recognize git
git credentialsId: credentialsId, url: 'git@host:repo.git', branch: params.BRANCH_NAME

//does not recognize currentBuild
currentBuild.description = "${params.BRANCH_NAME} @ ${rev}"
```

**Comment by bmustiata** [comment]
Except the `git` one, they all seem reasonable easy, but most likely they will be mocks only. I'll split them in more issues.

Thank you for the feedback.

**Comment by bmustiata** [comment]
Also an option, that might not be very fun, but still :) is to implement the commands as a plugin. - see https://github.com/bmustiata/jenny/blob/master/features/testset/plugin/vars/pluginCommand.groovy then configure the used plugin such as: https://github.com/bmustiata/jenny/blob/master/features/testset/parent/.jenny/config .

Everything except the exception should probably work like that.

**Comment by bmustiata** [comment]
The missing commands are now mocked with a noop operation.
