### ISSUE TITLE
improve sh functionality

### ISSUE THREAD

**Issue by dh-harald** [bmustiata/jenny#45]
Hi,

I'd like to use sh command to set a variable like this:
`def ret = sh(script: 'uname', returnStdout: true)`

Now I've got the following error message:
```
No signature of method: NodeAgent.sh() is applicable for argument types: (java.util.LinkedHashMap) values: [[script:uname, returnStdout:true]]
Possible solutions: sh(java.lang.String), is(java.lang.Object), use([Ljava.lang.Object;), pwd(), any(), any(groovy.lang.Closure)

```

Could you implement this feature?

Thanks!

**Comment by bmustiata** [comment]
I guess it was easier than I thought.
