### ISSUE TITLE
Is loading of shared liraries supported?

### ISSUE THREAD

**Issue by nekromant** [bmustiata/jenny#61]
Hello and thanks for creating jenny. I'm just getting started with it, and want to use it to debug my groovy shared library for jenkins. However I can't seem to get library loading to work. 
In my config I have:
```
libs: # list of libaries folders to load
  - libs/pipeline-library-demo
````

pipeline-library-demo is a clone of https://github.com/monodot/pipeline-library-demo

In my Jenkinsfile I put: 
```
@Library('pipeline-library-demo')_
```

And get a nice: 
```
1 ✗ necromant @ silverblade ~/Work/Basis/rumboot $ jenny 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Djdk.net.URLClassPath.disableClassPathURLCheck=true
> workspace: /tmp/jenny/workspace/rumboot/workspace
startup failed:
/home/necromant/Work/Basis/rumboot/Jenkinsfile: 1: unable to resolve class Library ,  unable to find class for annotation
 @ line 1, column 1.
   @Library('pipeline-library-demo')_
```

Looks like I'm missing some trivia. 

EDIT: 
```
library('pipeline-library-demo')
```
Looks like always null, no matter what I try.

**Comment by sjetha-pason** [comment]
I'm having this same issue as well. I'm not sure what needs to happen to get support for Shared Libraries added, but it would certainly be useful for our current situation.

**Comment by bmustiata** [comment]
Yes, the sharing of the libraries is supported, by just adding it in the `.jenny/config` in the `libs` array. This is in order to support also global libraries. I've added the `@Library` annotation, but it's a noop, so you don't get the annotation being missing error.

**Comment by nekromant** [comment]
Thanks a lot! Will give a try ASAP
